[package]
name = "enet"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.23"
ndarray = "0.15"
rand = "0.8"
rand_distr = "0.4"
tch = "0.2.0"
reqwest = { version = "0.11", features = ["blocking"] }
show-image = "0.13"
csv = "1.1"
